---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-22.04

trigger:
  - devolop

steps:
  - task: DotNetCoreCLI@2
    displayName: Build

    inputs:
      command: 'build'
      projects: src/NopCommerce.sln
      publishTestResults: true
      