---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

trigger:
  - develop

stages:  # stage1
  - stage: stage1 
    displayName: stage1 

    jobs:
      - job: build_mac
        displayName: build_mac

        steps:
          - script: 
              - echo hello shaik
              - echo Assalamualaikum shaik
              - echo Namaste shaik
              - echo vanakkkam shaik
              - echo namaskaram shaik

  - stage: stage2  # stage 2
    displayName: stage2

    jobs:
      - job: build_linux
        displayName: build_linux

        steps:
          - script: 
              - echo hello bro
              - echo Assalamualaikum bro
              - echo Namaste bro
              - echo vanakkkam bro
              - echo namaskaram bro
      
  - stage: stage3  # stage 3
    displayName: stage3

    jobs:
      - job: build_windows
        displayName: build_windows

        steps:
          - script: 
              - echo hello Anna
              - echo Assalamualaikum Anna
              - echo Namaste Anna
              - echo vanakkkam Anna
              - echo namaskaram Anna

  - stage: stage4  # stage 4
    displayName: stage4

    jobs:
      - job: build_unix
        displayName: build_unix

        steps:
          - script: 
              - echo hello bhai
              - echo Assalamualaikum bhai
              - echo Namaste bhai
              - echo vanakkkam bhai
              - echo namaskaram bhai



  